C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/inc/spi.h File Reference
Contains the spi peripheral manager API.
Functions
void SPI_Init (void)
Faz a iniciação do controlador e configura os respetivos pinos.
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Configures the transfer.
int SPI_Transfer (unsigned short *txBuffer, unsigned short *rxBuffer, int lenght)
Makes a transfer. Returns the success or error in the transfer.
Detailed Description
Contains the spi peripheral manager API.
Version
1.1
Date
17 Dec 2020
Author
Jose Filipe Cruz dos Santos
Function Documentation
SPI_ConfigTransfer()
void SPI_ConfigTransfer (int frequency, int bitData, int mode)
Configures the transfer.
Parameters
frequency send/reception frequency
bitData number of bits of changed data
mode transfer mode is a two bit value (1st bit = CPOL, 2nd bit = CPHA).
Definition at line 15 of file spi.c.
Referenced by ADXL345_Init().
SPI_Init()
void SPI_Init (void)
Faz a iniciação do controlador e configura os respetivos pinos.
Definition at line 7 of file spi.c.
Referenced by main().
SPI_Transfer()
int SPI_Transfer (unsigned short * txBuffer, unsigned short * rxBuffer, int lenght)
Makes a transfer. Returns the success or error in the transfer.
Parameters
txBuffer transfer ruffer contains transfer data
rxBuffer recieve buffer contains recieved data
length how many data is there to be transfered/recieved
Definition at line 35 of file spi.c.
Referenced by readRegister(), and writeRegister().