C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/CarRunner/inc/game.h File Reference
Functions
void gameInit ()
initializes the module
void gameRoutine (void)
routine that interfaces with buttons, lcd and accelerometer to play the game. It also saves scores and player names.
Function Documentation
gameInit()
void gameInit ()
initializes the module
Definition at line 30 of file game.c.
References car, and LCDText_CreateChar().
Referenced by main().
gameRoutine()
void gameRoutine (void)
routine that interfaces with buttons, lcd and accelerometer to play the game. It also saves scores and player names.
Definition at line 56 of file game.c.
References ADXL345_isTap(), BUTTON_GetButtonsEvents(), car, delay, initValues(), key_state::key, L, LCDText_Clear(), LCDText_Locate(), LCDText_Printf(), LCDText_WriteString(), points, PRESSED, R, readScores(), saveUser(), key_state::state, updateGameDesign(), updateGameLogic(), WAIT_ChronoUs(), and WAIT_GetElapsedMillis().
Referenced by main().