C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/src/button.c File Reference
#include `button.h`
#include `wait.h`
Macros
#define BUTTON_ONE 24
#define BUTTON_TWO 25
#define BUTTON_THREE 26
Functions
void BUTTON_Init (void)
Initializes every button and sets mode for to pull-up.
int BUTTON_Hit (void)
Gets pressed button non-blocking version.
int BUTTON_Read (void)
Blocks while button_Hit result equals -1.
 key_state BUTTON_GetButtonsEvents ()
Pressed button state.
Variables
 key_state keyState
Function Documentation
BUTTON_GetButtonsEvents()
 key_state BUTTON_GetButtonsEvents (void)
Pressed button state.
Returns
button state code (bitmap): pressed ,released , repeated
Definition at line 72 of file button.c.
References BUTTON_Hit(), and keyState.
Referenced by gameRoutine(), main(), Menu(), playerScoresShowDown(), saveUser(), and Time_changeRoutine().
BUTTON_Hit()
int BUTTON_Hit (void)
Gets pressed button non-blocking version.
Returns
button code (bitmap) if pressed otherwise -1
Definition at line 41 of file button.c.
References BUTTON_ONE, key_state::key, keyState, PRESSED, RELEASED, REPEATED, key_state::state, and WAIT_ChronoUs().
Referenced by BUTTON_GetButtonsEvents(), BUTTON_Init(), and BUTTON_Read().
BUTTON_Init()
void BUTTON_Init (void)
Initializes every button and sets mode for to pull-up.
Initializes the system to premit the access to buttons.
Definition at line 32 of file button.c.
References BUTTON_Hit(), BUTTON_ONE, and keyState.
Referenced by main().
BUTTON_Read()
int BUTTON_Read (void)
Blocks while button_Hit result equals -1.
Gets pressed button blocking version.
Definition at line 64 of file button.c.
References BUTTON_Hit().
Variable Documentation
keyState
 key_state keyState
Definition at line 27 of file button.c.
Referenced by BUTTON_GetButtonsEvents(), BUTTON_Hit(), BUTTON_Init(), main(), Menu(), and playerScoresShowDown().