C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/CarRunner/src/game.c File Reference
#include <stdbool.h>
#include <stdlib.h>
#include `game.h`
#include `saver.h`
#include `wait.h`
#include `lcd.h`
#include `button.h`
#include `CarRunner.h`
Macros
#define CAR 1
#define OBS 2
Functions
void gameInit ()
initializes the module
void gameRoutine ()
routine that interfaces with buttons, lcd and accelerometer to play the game. It also saves scores and player names.
void saveUser (int points)
void initValues ()
int updateGameLogic ()
void updateGameDesign ()
Variables
bool car = 0
bool upRoad [16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
bool downRoad [16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
int probabilityToSpawn = 20
int points = 0
int delay = 1000
Macro Definition Documentation
CAR
#define CAR 1
Definition at line 18 of file game.c.
OBS
#define OBS 2
Definition at line 19 of file game.c.
Function Documentation
gameInit()
void gameInit ()
initializes the module
Definition at line 30 of file game.c.
References car, and LCDText_CreateChar().
Referenced by main().
gameRoutine()
void gameRoutine (void)
routine that interfaces with buttons, lcd and accelerometer to play the game. It also saves scores and player names.
Definition at line 56 of file game.c.
References ADXL345_isTap(), BUTTON_GetButtonsEvents(), car, delay, initValues(), key_state::key, L, LCDText_Clear(), LCDText_Locate(), LCDText_Printf(), LCDText_WriteString(), points, PRESSED, R, readScores(), saveUser(), key_state::state, updateGameDesign(), updateGameLogic(), WAIT_ChronoUs(), and WAIT_GetElapsedMillis().
Referenced by main().
initValues()
void initValues ()
Definition at line 179 of file game.c.
References car, delay, downRoad, points, probabilityToSpawn, and upRoad.
Referenced by gameRoutine().
saveUser()
void saveUser (int points)
Definition at line 127 of file game.c.
References BUTTON_GetButtonsEvents(), key_state::key, L, LCDText_Clear(), LCDText_CursorOff(), LCDText_CursorOn(), LCDText_Locate(), LCDText_WriteChar(), LCDText_WriteString(), points, PRESSED, R, REPEATED, S, saveScore(), key_state::state, and WAIT_GetElapsedMillis().
Referenced by gameRoutine().
updateGameDesign()
void updateGameDesign ()
Definition at line 251 of file game.c.
References CAR, car, downRoad, LCDText_Locate(), LCDText_WriteString(), OBS, and upRoad.
Referenced by gameRoutine().
updateGameLogic()
int updateGameLogic ()
Definition at line 190 of file game.c.
References car, delay, downRoad, points, probabilityToSpawn, and upRoad.
Referenced by gameRoutine().
Variable Documentation
car
bool car = 0
Definition at line 23 of file game.c.
Referenced by gameInit(), gameRoutine(), initValues(), updateGameDesign(), and updateGameLogic().
delay
int delay = 1000
Definition at line 28 of file game.c.
Referenced by gameRoutine(), initValues(), and updateGameLogic().
downRoad
bool downRoad[16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
Definition at line 25 of file game.c.
Referenced by initValues(), updateGameDesign(), and updateGameLogic().
points
int points = 0
Definition at line 27 of file game.c.
Referenced by gameRoutine(), initValues(), saveUser(), and updateGameLogic().
probabilityToSpawn
int probabilityToSpawn = 20
Definition at line 26 of file game.c.
Referenced by initValues(), and updateGameLogic().
upRoad
bool upRoad[16] = {0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0}
Definition at line 24 of file game.c.
Referenced by initValues(), updateGameDesign(), and updateGameLogic().