WAIT Public Functions
Functions
int32_t WAIT_Init (void)
Initialises the wait API for 1 ms resolution.
void WAIT_Milliseconds (uint32_t millis)
Waits a number of milliseconds.
uint32_t WAIT_GetElapsedMillis (uint32_t start)
Get difference in milliseconds from parameter.
void WAIT_ChronoUs (uint32_t waitUs)
Waits waitUs microseconds.
Detailed Description
Function Documentation
WAIT_ChronoUs()
void WAIT_ChronoUs (uint32_t waitUs)
Waits waitUs microseconds.
Parameters
waitUs miliseconds to wait
Definition at line 50 of file wait.c.
Referenced by BUTTON_Hit(), gameRoutine(), LCDText_Clear(), LCDText_CreateChar(), LCDText_Init(), LCDText_WriteChar(), LCDText_WriteCmd(), LCDText_WriteNibble(), LCDText_WriteString(), and playerScoresShowDown().
WAIT_GetElapsedMillis()
uint32_t WAIT_GetElapsedMillis (uint32_t start)
Get difference in milliseconds from parameter.
Parameters
start if 0 get current milliseconds.
Definition at line 45 of file wait.c.
Referenced by gameRoutine(), main(), and saveUser().
WAIT_Init()
int32_t WAIT_Init (void)
Initialises the wait API for 1 ms resolution.
Returns
0 if initialisation successed; -1 if fails.
Note
This function must be called prior to any other WAIT functions, and use the SYSTICK resource.
Definition at line 32 of file wait.c.
References SYSTICK_FREQ.
Referenced by main().
WAIT_Milliseconds()
void WAIT_Milliseconds (uint32_t millis)
Waits a number of milliseconds.
Parameters
millis the whole number of milliseconds to wait.
Definition at line 24 of file wait.c.