C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/inc/ADXL345.h File Reference
Contains the ADXL345 API.
#include <stdbool.h>
Macros
#define ADXL345_DEVID_RESET_VALUE (0x00E5)
#define ADXL345_REG_DEVID (0x00)
#define ADXL345_REG_THRESH_TAP (0x1D)
#define ADXL345_REG_DUR (0x21)
#define ADXL345_REG_LATENT (0x22)
#define ADXL345_REG_WINDOW (0x23)
#define ADXL345_REG_THRESH_ACT (0x24)
#define ADXL345_REG_TAP_AXES (0x2A)
#define ADXL345_REG_ACT_TAP_STATUS (0x2B)
#define ADXL345_REG_BW_RATE (0x2C)
#define ADXL345_REG_POWER_CTL (0x2D)
#define ADXL345_REG_INT_ENABLE (0x2E)
#define ADXL345_REG_INT_MAP (0x2F)
#define ADXL345_REG_INT_SOURCE (0x30)
#define ADXL345_REG_DATA_FORMAT (0x31)
#define ADXL345_REG_DATAX0 (0x32)
#define ADXL345_REG_DATAX1 (0x33)
#define ADXL345_REG_DATAY0 (0x34)
#define ADXL345_REG_DATAY1 (0x35)
#define ADXL345_REG_DATAZ0 (0x36)
#define ADXL345_REG_DATAZ1 (0x37)
#define ADXL345_GRAVITY_SUN 273.95f
#define ADXL345_GRAVITY_EARTH 9.80665f
#define ADXL345_GRAVITY_MOON 1.622f
#define ADXL345_GRAVITY_MARS 3.69f
#define ADXL345_GRAVITY_NONE 1.00f
Enumerations
enum ADX345_DataRate_t {
 ADXL345_DATARATE_3200HZ = 0b1111,
 ADXL345_DATARATE_1600HZ = 0b1110,
 ADXL345_DATARATE_800HZ = 0b1101,
 ADXL345_DATARATE_400HZ = 0b1100,
 ADXL345_DATARATE_200HZ = 0b1011,
 ADXL345_DATARATE_100HZ = 0b1010,
 ADXL345_DATARATE_50HZ = 0b1001,
 ADXL345_DATARATE_25HZ = 0b1000,
 ADXL345_DATARATE_12_5HZ = 0b0111,
 ADXL345_DATARATE_6_25HZ = 0b0110,
 ADXL345_DATARATE_3_13HZ = 0b0101,
 ADXL345_DATARATE_1_56HZ = 0b0100,
 ADXL345_DATARATE_0_78HZ = 0b0011,
 ADXL345_DATARATE_0_39HZ = 0b0010,
 ADXL345_DATARATE_0_20HZ = 0b0001,
 ADXL345_DATARATE_0_10HZ = 0b0000
 }
enum ADX345_Range_t { ADXL345_RANGE_16G = 0b11,
 ADXL345_RANGE_8G = 0b10,
 ADXL345_RANGE_4G = 0b01,
 ADXL345_RANGE_2G = 0b00
 }
Functions
int ADXL345_Init (void)
Initializes the ADXL345 Peripheral.
void setupTap (float threshold, float duration, float latency, float window)
Configs taping.
bool ADXL345_isTap ()
Checks if it was tapped can't be use with ADXL345_isDoubleTap.
bool ADXL345_isDoubleTap ()
Checks if it was double tapped can't be use with ADXL345_isTap.
int ADXL345_Read (float *x_value, float *y_value, float *z_value)
Reads ADXL345 data.
Detailed Description
Contains the ADXL345 API.
Version
1.1
Date
8 Jan 2020
Author
Jose Filipe Cruz dos Santos
Enumeration Type Documentation
ADX345_DataRate_t
enum ADX345_DataRate_t
Data Rates
Enumerator
ADXL345_DATARATE_3200HZ
ADXL345_DATARATE_1600HZ
ADXL345_DATARATE_800HZ
ADXL345_DATARATE_400HZ
ADXL345_DATARATE_200HZ
ADXL345_DATARATE_100HZ
ADXL345_DATARATE_50HZ
ADXL345_DATARATE_25HZ
ADXL345_DATARATE_12_5HZ
ADXL345_DATARATE_6_25HZ
ADXL345_DATARATE_3_13HZ
ADXL345_DATARATE_1_56HZ
ADXL345_DATARATE_0_78HZ
ADXL345_DATARATE_0_39HZ
ADXL345_DATARATE_0_20HZ
ADXL345_DATARATE_0_10HZ
Definition at line 95 of file ADXL345.h.
ADX345_Range_t
enum ADX345_Range_t
Data Ranges
Enumerator
ADXL345_RANGE_16G
ADXL345_RANGE_8G
ADXL345_RANGE_4G
ADXL345_RANGE_2G
Definition at line 118 of file ADXL345.h.
Function Documentation
ADXL345_Init()
int ADXL345_Init (void)
Initializes the ADXL345 Peripheral.
Definition at line 37 of file ADXL345.c.
References ADXL345_DATARATE_100HZ, ADXL345_DEVID_RESET_VALUE, ADXL345_RANGE_2G, ADXL345_REG_BW_RATE, ADXL345_REG_DATA_FORMAT, ADXL345_REG_DEVID, ADXL345_REG_POWER_CTL, readRegister(), setupTap(), SPI_ConfigTransfer(), and writeRegister().
Referenced by main().
ADXL345_isDoubleTap()
bool ADXL345_isDoubleTap ()
Checks if it was double tapped can't be use with ADXL345_isTap.
Definition at line 118 of file ADXL345.c.
References ADXL345_REG_INT_SOURCE, and readRegister().
ADXL345_isTap()
bool ADXL345_isTap ()
Checks if it was tapped can't be use with ADXL345_isDoubleTap.
Definition at line 112 of file ADXL345.c.
References ADXL345_REG_INT_SOURCE, and readRegister().
Referenced by gameRoutine().
ADXL345_Read()
int ADXL345_Read (float * x_value, float * y_value, float * z_value)
Reads ADXL345 data.
Parameters
 out x_value x axis value
 out y_value y axis value
 out z_value z axis value
X value
Y value
Z value
Definition at line 124 of file ADXL345.c.
References ADXL345_REG_DATAX0, ADXL345_REG_DATAX1, ADXL345_REG_DATAY0, ADXL345_REG_DATAY1, ADXL345_REG_DATAZ0, ADXL345_REG_DATAZ1, and readRegister().
setupTap()
void setupTap (float threshold, float duration, float latency, float window)
Configs taping.
Parameters
treshold defines treshold
duration defines max duration of tap
latency defines latency for double tap
window defines window for double tap
Definition at line 78 of file ADXL345.c.
References ADXL345_REG_DUR, ADXL345_REG_INT_ENABLE, ADXL345_REG_INT_MAP, ADXL345_REG_LATENT, ADXL345_REG_TAP_AXES, ADXL345_REG_THRESH_TAP, ADXL345_REG_WINDOW, readRegister(), and writeRegister().
Referenced by ADXL345_Init().