C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/src/Flash.c File Reference
#include `Flash.h`
#include `LPC17xx.h`
Macros
#define IAP_LOCATION 0x1FFF1FF1
Typedefs
typedef void(* IAP) (unsigned int[], unsigned int[])
Functions
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Deletes the contents of a sector, or multiple sectors, of FLASH. To delete only one sector, the same sector number must be used for both parameters.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Write the data block. This Function can only access sectors from sector 16 to 29.
int FLASH_WriteBlock (void *dstAddr, void *srcAddr, unsigned int size)
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares the contents of the data block.
unsigned int FLASH_WriteArray (void *dstAddr, int srcAddr[], int array_size, unsigned int size)
Writes an array to a data block. This Function can only access sectors from sector 16 to 29.
unsigned int FLASH_BlanckCheck (unsigned int startSector, unsigned int endSector)
Variables
 IAP iap_entry = (IAP) IAP_LOCATION
Macro Definition Documentation
IAP_LOCATION
#define IAP_LOCATION 0x1FFF1FF1
Definition at line 12 of file Flash.c.
Typedef Documentation
IAP
typedef void(* IAP) (unsigned int[], unsigned int[])
Definition at line 13 of file Flash.c.
Function Documentation
FLASH_BlanckCheck()
unsigned int FLASH_BlanckCheck (unsigned int startSector, unsigned int endSector)
Definition at line 115 of file Flash.c.
References iap_entry.
Referenced by checkClean().
FLASH_EraseSectors()
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Deletes the contents of a sector, or multiple sectors, of FLASH. To delete only one sector, the same sector number must be used for both parameters.
Definition at line 16 of file Flash.c.
References IAP_CMD_SUCESS, and iap_entry.
Referenced by FLASH_WriteArray(), and FLASH_WriteData().
FLASH_VerifyData()
unsigned int FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Compares the contents of the data block.
Parameters
srcAddr data block reference
size size in bytes of the data block
dstAddr data block to be compared to
Definition at line 70 of file Flash.c.
References iap_entry.
FLASH_WriteArray()
unsigned int FLASH_WriteArray (void * dstAddr, int srcAddr[], int array_size, unsigned int size)
Writes an array to a data block. This Function can only access sectors from sector 16 to 29.
Parameters
srcAddr array to be written
array_size size of the array
size block size
dstAddr Flash address
Definition at line 83 of file Flash.c.
References FLASH_EraseSectors(), IAP_CMD_SUCESS, iap_entry, and SECTOR_SIZE.
Referenced by saveScore().
FLASH_WriteBlock()
int FLASH_WriteBlock (void * dstAddr, void * srcAddr, unsigned int size)
Definition at line 53 of file Flash.c.
References iap_entry.
Referenced by FLASH_WriteData().
FLASH_WriteData()
unsigned int FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Write the data block. This Function can only access sectors from sector 16 to 29.
Parameters
srcAddr data block pointer
size block size
dstAddr Flash address
Definition at line 36 of file Flash.c.
References FLASH_EraseSectors(), FLASH_WriteBlock(), IAP_CMD_SUCESS, iap_entry, and SECTOR_SIZE.
Referenced by checkClean().
Variable Documentation
iap_entry
 IAP iap_entry = (IAP) IAP_LOCATION
Definition at line 14 of file Flash.c.
Referenced by FLASH_BlanckCheck(), FLASH_EraseSectors(), FLASH_VerifyData(), FLASH_WriteArray(), FLASH_WriteBlock(), and FLASH_WriteData().