C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/CarRunner/inc/time_helper.h File Reference
#include `rtc.h`
Functions
void Time_changeRoutine (time_t seconds)
routine that interfaces with lcd and buttons to change time in rtc
void update_DateTimeDisplay (struct tm datetime)
updates lcd with date and time
Function Documentation
Time_changeRoutine()
void Time_changeRoutine (time_t seconds)
routine that interfaces with lcd and buttons to change time in rtc
Parameters
seconds starting time
Definition at line 30 of file time_helper.c.
References BUTTON_GetButtonsEvents(), key_state::key, LCDText_Clear(), LCDText_CursorOff(), LCDText_CursorOn(), LCDText_Locate(), LCDText_WriteString(), PRESSED, RTC_SetValue(), key_state::state, and update_DateTimeDisplay().
Referenced by routineChooser().
update_DateTimeDisplay()
void update_DateTimeDisplay (struct tm datetime)
updates lcd with date and time
Parameters
datetime time to be displayed
Definition at line 85 of file time_helper.c.
References LCDText_Locate(), and LCDText_WriteString().
Referenced by main(), and Time_changeRoutine().