C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/inc/button.h File Reference
Contains the button API.
Data Structures
struct key_state
Macros
#define PRESSED 0
#define RELEASED 1
#define REPEATED 2
Functions
void BUTTON_Init (void)
Initializes the system to premit the access to buttons.
int BUTTON_Hit (void)
Gets pressed button non-blocking version.
int BUTTON_Read (void)
Gets pressed button blocking version.
 key_state BUTTON_GetButtonsEvents (void)
Pressed button state.
Detailed Description
Contains the button API.
Version
1.1
Date
3 Nov 2020
Author
Jose Filipe Cruz dos Santos
Macro Definition Documentation
PRESSED
#define PRESSED 0
Definition at line 13 of file button.h.
RELEASED
#define RELEASED 1
Definition at line 14 of file button.h.
REPEATED
#define REPEATED 2
Definition at line 15 of file button.h.
Function Documentation
BUTTON_GetButtonsEvents()
 key_state BUTTON_GetButtonsEvents (void)
Pressed button state.
Returns
button state code (bitmap): pressed ,released , repeated
Definition at line 72 of file button.c.
References BUTTON_Hit(), and keyState.
Referenced by gameRoutine(), main(), Menu(), playerScoresShowDown(), saveUser(), and Time_changeRoutine().
BUTTON_Hit()
int BUTTON_Hit (void)
Gets pressed button non-blocking version.
Returns
button code (bitmap) if pressed otherwise -1
Definition at line 41 of file button.c.
References BUTTON_ONE, key_state::key, keyState, PRESSED, RELEASED, REPEATED, key_state::state, and WAIT_ChronoUs().
Referenced by BUTTON_GetButtonsEvents(), BUTTON_Init(), and BUTTON_Read().
BUTTON_Init()
void BUTTON_Init (void)
Initializes the system to premit the access to buttons.
Initializes the system to premit the access to buttons.
Definition at line 32 of file button.c.
References BUTTON_Hit(), BUTTON_ONE, and keyState.
Referenced by main().
BUTTON_Read()
int BUTTON_Read (void)
Gets pressed button blocking version.
Returns
button code (bitmap) when pressed
Gets pressed button blocking version.
Definition at line 64 of file button.c.
References BUTTON_Hit().