C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/CarRunner/src/saver.c File Reference
#include <stdlib.h>
#include `saver.h`
#include `flash.h`
Functions
void checkClean ()
void saveScore (int score, char *name, int name_size)
int * readScores ()
reads from flash all the scores
int listSize ()
void readNames (char *strings[])
function that reads from flash all the names its required that strings is started with size[listSize][17] to accommodate for max size names
Variables
int * names = sector28
int * scores = sector29
int zero = 0
Function Documentation
checkClean()
void checkClean ()
Definition at line 15 of file saver.c.
References FLASH_BlanckCheck(), FLASH_WriteData(), IAP_SECTOR_NOT_BLANK, names, scores, and zero.
Referenced by listSize(), readScores(), and saveScore().
listSize()
int listSize ()
Returns
the current number of players that exist
Definition at line 83 of file saver.c.
References checkClean(), and names.
Referenced by playerScoresShowDown().
readNames()
void readNames (char * strings[])
function that reads from flash all the names its required that strings is started with size[listSize][17] to accommodate for max size names
Definition at line 89 of file saver.c.
References names.
Referenced by playerScoresShowDown().
readScores()
int* readScores ()
reads from flash all the scores
Returns
array of scores
Definition at line 70 of file saver.c.
References checkClean(), and scores.
Referenced by gameRoutine(), and playerScoresShowDown().
saveScore()
void saveScore (int score, char * name, int name_size)
Definition at line 22 of file saver.c.
References checkClean(), FLASH_WriteArray(), IAP_CMD_SUCESS, names, and scores.
Referenced by saveUser().
Variable Documentation
names
int* names = sector28
Definition at line 11 of file saver.c.
Referenced by checkClean(), listSize(), readNames(), and saveScore().
scores
int* scores = sector29
Definition at line 12 of file saver.c.
Referenced by checkClean(), playerScoresShowDown(), readScores(), and saveScore().
zero
int zero = 0
Definition at line 13 of file saver.c.
Referenced by checkClean().