C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/src/lcd.c File Reference
#include `lcd.h`
#include `wait.h`
#include <stdarg.h>
#include <stdio.h>
Macros
#define EN 0
#define RS 1
#define DB4 6
Functions
void LCDText_WriteNibble (char data, unsigned int rs)
void LCDText_WriteByte (char data, unsigned int rs)
void LCDText_Init (void)
Initiates the system to allow access to the LCD peripheral, using 2 lines with 16 columns and 4-bit communication.
void LCDText_CreateChar (unsigned char location, unsigned char charmap[])
Creates a character.
void LCDText_WriteCmd (char cmd)
Gives an instruction to the LCD controller.
void LCDText_WriteChar (char ch)
Writes a character at the current cursor position.
void LCDText_WriteString (char *str)
Writes a string at the current cursor position.
void LCDText_Locate (int row, int column)
Positions the cursor on the row and column of the display.
void LCDText_Clear (void)
Clear the display using the command available in the peripheral API.
void LCDText_Printf (char *fmt,...)
Writes the string fmt at the current cursor position.
void LCDText_CursorOn ()
Turns on display cursor on.
void LCDText_CursorOff ()
Turns on display cursor off.
Variables
int x
int y
Macro Definition Documentation
DB4
#define DB4 6
Definition at line 19 of file lcd.c.
EN
#define EN 0
Definition at line 17 of file lcd.c.
RS
#define RS 1
Definition at line 18 of file lcd.c.
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Clear the display using the command available in the peripheral API.
Definition at line 129 of file lcd.c.
References LCDText_CMD_DISPLAY_CLEAR, LCDText_Locate(), LCDText_WriteCmd(), and WAIT_ChronoUs().
Referenced by gameRoutine(), LCDText_Init(), Menu(), playerScoresShowDown(), saveUser(), and Time_changeRoutine().
LCDText_CreateChar()
void LCDText_CreateChar (unsigned char location, unsigned char charmap[])
Creates a character.
Parameters
location position in the character table
charmap character design
Definition at line 69 of file lcd.c.
References LCDText_WriteByte(), LCDText_WriteCmd(), and WAIT_ChronoUs().
Referenced by gameInit(), and LCDText_Init().
LCDText_CursorOff()
void LCDText_CursorOff ()
Turns on display cursor off.
Definition at line 148 of file lcd.c.
References LCDText_CMD_DISPLAY_ON, and LCDText_WriteCmd().
Referenced by saveUser(), and Time_changeRoutine().
LCDText_CursorOn()
void LCDText_CursorOn ()
Turns on display cursor on.
Definition at line 144 of file lcd.c.
References LCDText_CMD_DISPLAY_ON, and LCDText_WriteCmd().
Referenced by saveUser(), and Time_changeRoutine().
LCDText_Init()
void LCDText_Init (void)
Initiates the system to allow access to the LCD peripheral, using 2 lines with 16 columns and 4-bit communication.
Definition at line 45 of file lcd.c.
References DB4, EN, LCDText_Clear(), LCDText_CMD_DISPLAY_OFF, LCDText_CMD_DISPLAY_ON, LCDText_CMD_ENTRY_MODE_SET, LCDText_CMD_FUNCTION_SET, LCDText_CreateChar(), LCDText_Locate(), LCDText_WriteCmd(), LCDText_WriteNibble(), RS, and WAIT_ChronoUs().
Referenced by main().
LCDText_Locate()
void LCDText_Locate (int row, int column)
Positions the cursor on the row and column of the display.
Coloca o cursor na posicao (x,y)
Parameters
row from 1 to 2
column from 0 to 15
Definition at line 114 of file lcd.c.
References LCDText_CMD_SET_DDRAM_ADDR, LCDText_COLUMNS, LCDText_LINE_OFFSET, LCDText_LINES, LCDText_WriteCmd(), x, and y.
Referenced by gameRoutine(), LCDText_Clear(), LCDText_Init(), LCDText_WriteString(), saveUser(), Time_changeRoutine(), update_DateTimeDisplay(), and updateGameDesign().
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Writes the string fmt at the current cursor position.
Parameters
fmt format of the string
Definition at line 135 of file lcd.c.
References LCDText_WriteString().
Referenced by gameRoutine(), and playerScoresShowDown().
LCDText_WriteByte()
void LCDText_WriteByte (char data, unsigned int rs)
Definition at line 40 of file lcd.c.
References LCDText_WriteNibble().
Referenced by LCDText_CreateChar(), LCDText_WriteChar(), and LCDText_WriteCmd().
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes a character at the current cursor position.
Definition at line 86 of file lcd.c.
References LCDText_DATA, LCDText_WriteByte(), WAIT_ChronoUs(), and x.
Referenced by LCDText_WriteString(), and saveUser().
LCDText_WriteCmd()
void LCDText_WriteCmd (char cmd)
Gives an instruction to the LCD controller.
Definition at line 81 of file lcd.c.
References LCDText_CMD, LCDText_WriteByte(), and WAIT_ChronoUs().
Referenced by LCDText_Clear(), LCDText_CreateChar(), LCDText_CursorOff(), LCDText_CursorOn(), LCDText_Init(), and LCDText_Locate().
LCDText_WriteNibble()
void LCDText_WriteNibble (char data, unsigned int rs)
Definition at line 23 of file lcd.c.
References DB4, EN, RS, and WAIT_ChronoUs().
Referenced by LCDText_Init(), and LCDText_WriteByte().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes a string at the current cursor position.
Definition at line 92 of file lcd.c.
References LCDText_COLUMNS, LCDText_LINES, LCDText_Locate(), LCDText_WriteChar(), WAIT_ChronoUs(), x, and y.
Referenced by gameRoutine(), LCDText_Printf(), Menu(), playerScoresShowDown(), saveUser(), Time_changeRoutine(), update_DateTimeDisplay(), and updateGameDesign().
Variable Documentation
x
int x
Definition at line 21 of file lcd.c.
Referenced by LCDText_Locate(), LCDText_WriteChar(), and LCDText_WriteString().
y
int y
Definition at line 21 of file lcd.c.
Referenced by LCDText_Locate(), and LCDText_WriteString().