C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/CarRunner/inc/saver.h File Reference
Functions
void saveScore (int score, char *name, int name_size)
int * readScores ()
reads from flash all the scores
int listSize ()
void readNames (char *strings[])
function that reads from flash all the names its required that strings is started with size[listSize][17] to accommodate for max size names
Function Documentation
listSize()
int listSize ()
Returns
the current number of players that exist
Definition at line 83 of file saver.c.
References checkClean(), and names.
Referenced by playerScoresShowDown().
readNames()
void readNames (char * strings[])
function that reads from flash all the names its required that strings is started with size[listSize][17] to accommodate for max size names
Definition at line 89 of file saver.c.
References names.
Referenced by playerScoresShowDown().
readScores()
int* readScores ()
reads from flash all the scores
Returns
array of scores
Definition at line 70 of file saver.c.
References checkClean(), and scores.
Referenced by gameRoutine(), and playerScoresShowDown().
saveScore()
void saveScore (int score, char * name, int name_size)
Definition at line 22 of file saver.c.
References checkClean(), FLASH_WriteArray(), IAP_CMD_SUCESS, names, and scores.
Referenced by saveUser().