C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/inc/rtc.h File Reference
Contains the rtc peripheral manager API.
#include `time.h`
Functions
void RTC_Init (time_t seconds)
Initiates the system to allow access to the RTC peripheral.
void RTC_GetValue (struct tm *dateTime)
void RTC_SetValue (struct tm *dateTime)
Updates RTC.
void RTC_SetSeconds (time_t seconds)
Performs the RTC update with the value of the seconds parameter.
time_t RTC_GetSeconds (void)
Detailed Description
Contains the rtc peripheral manager API.
Version
1.1
Date
3 Nov 2020
Author
Jose Filipe Cruz dos Santos
Function Documentation
RTC_GetSeconds()
time_t RTC_GetSeconds (void)
Returns
Returns the current value of the RTC, in seconds since 00:00:00 UTC on January 1 1970
Definition at line 64 of file rtc.c.
References RTC_GetValue().
Referenced by routineChooser().
RTC_GetValue()
void RTC_GetValue (struct tm * dateTime)
Parameters
 out dateTime current RTC value ajusted to 00:00:00 UTC from 1 January 1970.
Definition at line 25 of file rtc.c.
Referenced by main(), and RTC_GetSeconds().
RTC_Init()
void RTC_Init (time_t seconds)
Initiates the system to allow access to the RTC peripheral.
Parameters
seconds The RTC is started with this value, which represents the seconds since 00:00:00 UTC from 1 January 1970.
Definition at line 14 of file rtc.c.
References RTC_SetSeconds().
Referenced by main().
RTC_SetSeconds()
void RTC_SetSeconds (time_t seconds)
Performs the RTC update with the value of the seconds parameter.
Parameters
seconds represents the seconds since 00:00:00 UTC of 1 January 1970.
Definition at line 59 of file rtc.c.
References RTC_SetValue().
Referenced by RTC_Init().
RTC_SetValue()
void RTC_SetValue (struct tm * dateTime)
Updates RTC.
Parameters
dateTime value that is set to update RTC.
Definition at line 45 of file rtc.c.
Referenced by RTC_SetSeconds(), and Time_changeRoutine().