C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/src/ADXL345.c File Reference
#include `ADXL345.h`
#include `spi.h`
#include `LPC17xx.h`
Macros
#define constrain(amt, low, high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
Functions
void writeRegister (unsigned short reg, unsigned short value)
void readRegisters (unsigned short *reg, unsigned short value, int size)
void readRegister (unsigned short reg, unsigned short *retValue)
int ADXL345_Init ()
Initializes the ADXL345 Peripheral.
void setupTap (float threshold, float duration, float latency, float window)
Configs taping.
bool ADXL345_isTap ()
Checks if it was tapped can't be use with ADXL345_isDoubleTap.
bool ADXL345_isDoubleTap ()
Checks if it was double tapped can't be use with ADXL345_isTap.
int ADXL345_Read (float *x_value, float *y_value, float *z_value)
Reads ADXL345 data.
Macro Definition Documentation
constrain
#define constrain(amt, low, high) ((amt)<(low)?(low):((amt)>(high)?(high):(amt)))
Definition at line 5 of file ADXL345.c.
Function Documentation
ADXL345_Init()
int ADXL345_Init (void)
Initializes the ADXL345 Peripheral.
Definition at line 37 of file ADXL345.c.
References ADXL345_DATARATE_100HZ, ADXL345_DEVID_RESET_VALUE, ADXL345_RANGE_2G, ADXL345_REG_BW_RATE, ADXL345_REG_DATA_FORMAT, ADXL345_REG_DEVID, ADXL345_REG_POWER_CTL, readRegister(), setupTap(), SPI_ConfigTransfer(), and writeRegister().
Referenced by main().
ADXL345_isDoubleTap()
bool ADXL345_isDoubleTap ()
Checks if it was double tapped can't be use with ADXL345_isTap.
Definition at line 118 of file ADXL345.c.
References ADXL345_REG_INT_SOURCE, and readRegister().
ADXL345_isTap()
bool ADXL345_isTap ()
Checks if it was tapped can't be use with ADXL345_isDoubleTap.
Definition at line 112 of file ADXL345.c.
References ADXL345_REG_INT_SOURCE, and readRegister().
Referenced by gameRoutine().
ADXL345_Read()
int ADXL345_Read (float * x_value, float * y_value, float * z_value)
Reads ADXL345 data.
Parameters
 out x_value x axis value
 out y_value y axis value
 out z_value z axis value
X value
Y value
Z value
Definition at line 124 of file ADXL345.c.
References ADXL345_REG_DATAX0, ADXL345_REG_DATAX1, ADXL345_REG_DATAY0, ADXL345_REG_DATAY1, ADXL345_REG_DATAZ0, ADXL345_REG_DATAZ1, and readRegister().
readRegister()
void readRegister (unsigned short reg, unsigned short * retValue)
Definition at line 23 of file ADXL345.c.
References SPI_Transfer().
Referenced by ADXL345_Init(), ADXL345_isDoubleTap(), ADXL345_isTap(), ADXL345_Read(), and setupTap().
readRegisters()
void readRegisters (unsigned short * reg, unsigned short value, int size)
Definition at line 19 of file ADXL345.c.
setupTap()
void setupTap (float threshold, float duration, float latency, float window)
Configs taping.
Parameters
treshold defines treshold
duration defines max duration of tap
latency defines latency for double tap
window defines window for double tap
Definition at line 78 of file ADXL345.c.
References ADXL345_REG_DUR, ADXL345_REG_INT_ENABLE, ADXL345_REG_INT_MAP, ADXL345_REG_LATENT, ADXL345_REG_TAP_AXES, ADXL345_REG_THRESH_TAP, ADXL345_REG_WINDOW, readRegister(), and writeRegister().
Referenced by ADXL345_Init().
writeRegister()
void writeRegister (unsigned short reg, unsigned short value)
Definition at line 7 of file ADXL345.c.
References SPI_Transfer().
Referenced by ADXL345_Init(), and setupTap().