C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/inc/lcd.h File Reference
Contains the flash API.
Macros
#define LCDText_LINES 2
#define LCDText_COLUMNS 16
#define LCDText_LINE_OFFSET 0x40
#define LCDText_CMD 0
#define LCDText_DATA 1
#define LCDText_CMD_DISPLAY_OFF 0x08
#define LCDText_CMD_DISPLAY_ON 0x0C
#define LCDText_CMD_DISPLAY_CLEAR 1
#define LCDText_CMD_ENTRY_MODE_SET 0x06
#define LCDText_CMD_FUNCTION_SET 0x28
#define LCDText_CMD_RETURN_HOME 2
#define LCDText_CMD_SET_DDRAM_ADDR 0x80
Functions
void LCDText_WriteCmd (char cmd)
Gives an instruction to the LCD controller.
void LCDText_WriteChar (char ch)
Writes a character at the current cursor position.
void LCDText_Init (void)
Initiates the system to allow access to the LCD peripheral, using 2 lines with 16 columns and 4-bit communication.
void LCDText_WriteString (char *str)
Writes a string at the current cursor position.
void LCDText_Locate (int row, int column)
Positions the cursor on the row and column of the display.
void LCDText_Clear (void)
Clear the display using the command available in the peripheral API.
void LCDText_CreateChar (unsigned char location, unsigned char charmap[])
Creates a character.
void LCDText_Printf (char *fmt,...)
Writes the string fmt at the current cursor position.
void LCDText_CursorOn ()
Turns on display cursor on.
void LCDText_CursorOff ()
Turns on display cursor off.
Detailed Description
Contains the flash API.
Contains the lcd API.
Version
1.1
Date
12 Jan 2020
Author
Jose Filipe Cruz dos Santos
Version
1.1
Date
17 Nov 2020
Author
Jose Filipe Cruz dos Santos
Macro Definition Documentation
LCDText_CMD
#define LCDText_CMD 0
Definition at line 27 of file lcd.h.
LCDText_DATA
#define LCDText_DATA 1
Definition at line 28 of file lcd.h.
LCDText_LINE_OFFSET
#define LCDText_LINE_OFFSET 0x40
DISPLAY_DDRAM_ADDRESSING_OFFSET
Definition at line 25 of file lcd.h.
Function Documentation
LCDText_Clear()
void LCDText_Clear (void)
Clear the display using the command available in the peripheral API.
Definition at line 129 of file lcd.c.
References LCDText_CMD_DISPLAY_CLEAR, LCDText_Locate(), LCDText_WriteCmd(), and WAIT_ChronoUs().
Referenced by gameRoutine(), LCDText_Init(), Menu(), playerScoresShowDown(), saveUser(), and Time_changeRoutine().
LCDText_CreateChar()
void LCDText_CreateChar (unsigned char location, unsigned char charmap[])
Creates a character.
Parameters
location position in the character table
charmap character design
Definition at line 69 of file lcd.c.
References LCDText_WriteByte(), LCDText_WriteCmd(), and WAIT_ChronoUs().
Referenced by gameInit(), and LCDText_Init().
LCDText_CursorOff()
void LCDText_CursorOff ()
Turns on display cursor off.
Definition at line 148 of file lcd.c.
References LCDText_CMD_DISPLAY_ON, and LCDText_WriteCmd().
Referenced by saveUser(), and Time_changeRoutine().
LCDText_CursorOn()
void LCDText_CursorOn ()
Turns on display cursor on.
Definition at line 144 of file lcd.c.
References LCDText_CMD_DISPLAY_ON, and LCDText_WriteCmd().
Referenced by saveUser(), and Time_changeRoutine().
LCDText_Init()
void LCDText_Init (void)
Initiates the system to allow access to the LCD peripheral, using 2 lines with 16 columns and 4-bit communication.
Definition at line 45 of file lcd.c.
References DB4, EN, LCDText_Clear(), LCDText_CMD_DISPLAY_OFF, LCDText_CMD_DISPLAY_ON, LCDText_CMD_ENTRY_MODE_SET, LCDText_CMD_FUNCTION_SET, LCDText_CreateChar(), LCDText_Locate(), LCDText_WriteCmd(), LCDText_WriteNibble(), RS, and WAIT_ChronoUs().
Referenced by main().
LCDText_Locate()
void LCDText_Locate (int row, int column)
Positions the cursor on the row and column of the display.
Coloca o cursor na posicao (x,y)
Parameters
row from 1 to 2
column from 0 to 15
Definition at line 114 of file lcd.c.
References LCDText_CMD_SET_DDRAM_ADDR, LCDText_COLUMNS, LCDText_LINE_OFFSET, LCDText_LINES, LCDText_WriteCmd(), x, and y.
Referenced by gameRoutine(), LCDText_Clear(), LCDText_Init(), LCDText_WriteString(), saveUser(), Time_changeRoutine(), update_DateTimeDisplay(), and updateGameDesign().
LCDText_Printf()
void LCDText_Printf (char * fmt, ...)
Writes the string fmt at the current cursor position.
Parameters
fmt format of the string
Definition at line 135 of file lcd.c.
References LCDText_WriteString().
Referenced by gameRoutine(), and playerScoresShowDown().
LCDText_WriteChar()
void LCDText_WriteChar (char ch)
Writes a character at the current cursor position.
Definition at line 86 of file lcd.c.
References LCDText_DATA, LCDText_WriteByte(), WAIT_ChronoUs(), and x.
Referenced by LCDText_WriteString(), and saveUser().
LCDText_WriteCmd()
void LCDText_WriteCmd (char cmd)
Gives an instruction to the LCD controller.
Definition at line 81 of file lcd.c.
References LCDText_CMD, LCDText_WriteByte(), and WAIT_ChronoUs().
Referenced by LCDText_Clear(), LCDText_CreateChar(), LCDText_CursorOff(), LCDText_CursorOn(), LCDText_Init(), and LCDText_Locate().
LCDText_WriteString()
void LCDText_WriteString (char * str)
Writes a string at the current cursor position.
Definition at line 92 of file lcd.c.
References LCDText_COLUMNS, LCDText_LINES, LCDText_Locate(), LCDText_WriteChar(), WAIT_ChronoUs(), x, and y.
Referenced by gameRoutine(), LCDText_Printf(), Menu(), playerScoresShowDown(), saveUser(), Time_changeRoutine(), update_DateTimeDisplay(), and updateGameDesign().