C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/SE2021/inc/Flash.h File Reference
Macros
#define IAP_CMD_SUCESS 0
#define IAP_INVALID_COMMAND 1
#define IAP_SRC_ADDR_ERROR 2
#define IAP_DST_ADDR_ERROR 3
#define IAP_SRC_ADDR_NOT_MAPPED 4
#define IAP_DST_ADDR_NOT_MAPPED 5
#define IAP_COUNT_ERROR 6
#define IAP_INVALID_SECTOR 7
#define IAP_SECTOR_NOT_BLANK 8
#define IAP_SECTOR_NOT_PREPARED_FOR_WRITE_OPERATION 9
#define IAP_COMPARE_ERROR 10
#define IAP_BUSY 11
#define SECTOR_SIZE 32768
#define sector28 0x00070000
#define sector29 0x00078000
Functions
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Deletes the contents of a sector, or multiple sectors, of FLASH. To delete only one sector, the same sector number must be used for both parameters.
unsigned int FLASH_WriteData (void *dstAddr, void *srcAddr, unsigned int size)
Write the data block. This Function can only access sectors from sector 16 to 29.
unsigned int FLASH_VerifyData (void *dstAddr, void *srcAddr, unsigned int size)
Compares the contents of the data block.
unsigned int FLASH_WriteArray (void *dstAddr, int srcAddr[], int array_size, unsigned int size)
Writes an array to a data block. This Function can only access sectors from sector 16 to 29.
int FLASH_WriteBlock (void *dstAddr, void *srcAddr, unsigned int size)
unsigned int FLASH_BlanckCheck (unsigned int startSector, unsigned int endSector)
Macro Definition Documentation
sector28
#define sector28 0x00070000
Sector 28 adrress
Definition at line 36 of file Flash.h.
sector29
#define sector29 0x00078000
Sector 29 adrress
Definition at line 39 of file Flash.h.
SECTOR_SIZE
#define SECTOR_SIZE 32768
Sectors sizes
Definition at line 33 of file Flash.h.
Function Documentation
FLASH_BlanckCheck()
unsigned int FLASH_BlanckCheck (unsigned int startSector, unsigned int endSector)
Definition at line 115 of file Flash.c.
References iap_entry.
Referenced by checkClean().
FLASH_EraseSectors()
unsigned int FLASH_EraseSectors (unsigned int startSector, unsigned int endSector)
Deletes the contents of a sector, or multiple sectors, of FLASH. To delete only one sector, the same sector number must be used for both parameters.
Definition at line 16 of file Flash.c.
References IAP_CMD_SUCESS, and iap_entry.
Referenced by FLASH_WriteArray(), and FLASH_WriteData().
FLASH_VerifyData()
unsigned int FLASH_VerifyData (void * dstAddr, void * srcAddr, unsigned int size)
Compares the contents of the data block.
Parameters
srcAddr data block reference
size size in bytes of the data block
dstAddr data block to be compared to
Definition at line 70 of file Flash.c.
References iap_entry.
FLASH_WriteArray()
unsigned int FLASH_WriteArray (void * dstAddr, int srcAddr[], int array_size, unsigned int size)
Writes an array to a data block. This Function can only access sectors from sector 16 to 29.
Parameters
srcAddr array to be written
array_size size of the array
size block size
dstAddr Flash address
Definition at line 83 of file Flash.c.
References FLASH_EraseSectors(), IAP_CMD_SUCESS, iap_entry, and SECTOR_SIZE.
Referenced by saveScore().
FLASH_WriteBlock()
int FLASH_WriteBlock (void * dstAddr, void * srcAddr, unsigned int size)
Definition at line 53 of file Flash.c.
References iap_entry.
Referenced by FLASH_WriteData().
FLASH_WriteData()
unsigned int FLASH_WriteData (void * dstAddr, void * srcAddr, unsigned int size)
Write the data block. This Function can only access sectors from sector 16 to 29.
Parameters
srcAddr data block pointer
size block size
dstAddr Flash address
Definition at line 36 of file Flash.c.
References FLASH_EraseSectors(), FLASH_WriteBlock(), IAP_CMD_SUCESS, iap_entry, and SECTOR_SIZE.
Referenced by checkClean().