C:/Users/josee/Documents/ISEL/3_Ano-5_Semestre/SE1/CarRunner/src/CarRunner.c File Reference
#include <cr_section_macros.h>
#include <stdio.h>
#include <stdlib.h>
#include `lcd.h`
#include `time_helper.h`
#include `button.h`
#include `rtc.h`
#include `wait.h`
#include `ADXL345.h`
#include `spi.h`
#include `saver.h`
#include `CarRunner.h`
Macros
#define PRESSING_TIME 2000
Functions
int main (void)
void Menu ()
void routineChooser (int routine)
void playerScoresShowDown ()
Variables
char * menu_options [3] = {`Change Time`,`Show Players\nScores`, `Exit`}
Macro Definition Documentation
PRESSING_TIME
#define PRESSING_TIME 2000
Definition at line 30 of file CarRunner.c.
Function Documentation
main()
int main (void)
Definition at line 47 of file CarRunner.c.
References ADXL345_Init(), BUTTON_GetButtonsEvents(), BUTTON_Init(), gameInit(), gameRoutine(), key_state::key, keyState, L, LCDText_Init(), Menu(), PRESSED, PRESSING_TIME, R, REPEATED, RTC_GetValue(), RTC_Init(), S, SPI_Init(), key_state::state, update_DateTimeDisplay(), WAIT_GetElapsedMillis(), and WAIT_Init().
Menu()
void Menu ()
Definition at line 109 of file CarRunner.c.
References BUTTON_GetButtonsEvents(), key_state::key, keyState, L, LCDText_Clear(), LCDText_WriteString(), menu_options, PRESSED, R, routineChooser(), S, and key_state::state.
Referenced by main().
playerScoresShowDown()
void playerScoresShowDown ()
Definition at line 176 of file CarRunner.c.
References BUTTON_GetButtonsEvents(), key_state::key, keyState, L, LCDText_Clear(), LCDText_Printf(), LCDText_WriteString(), listSize(), PRESSED, R, readNames(), readScores(), S, scores, key_state::state, and WAIT_ChronoUs().
Referenced by routineChooser().
routineChooser()
void routineChooser (int routine)
Definition at line 150 of file CarRunner.c.
References playerScoresShowDown(), RTC_GetSeconds(), and Time_changeRoutine().
Referenced by Menu().
Variable Documentation
menu_options
char* menu_options[3] = {`Change Time`,`Show Players\nScores`, `Exit`}
Definition at line 93 of file CarRunner.c.
Referenced by Menu().